### ISSUE TITLE
usage for non-reference video quality estimation

### ISSUE THREAD

**Issue by chatdeschroedinger** [Ericsson/PXNR-No-reference-video-quality-estimation#8]
Hi,

Thank you for this great implementation of a non-reference-video-quality-estimation.
I am considering using this estimator for my thesis.
Is it correct that we can use an mp4 video file as input and receive a MOS score estimation or is there preprocessing/feature extraction required on the video?

And finally is there a published article on this work?

Thank you for your answer

**Comment by davidlindero** [comment]
Hello, and thank you for your interest :) 

First of all, running the model in its current state is VERY RAM intensive. So make sure that you have a system with 30+ GBs for running it for even a short video. This implementation is pretty "brute force" and could definitely be improved.  

Yes, the model itself can handle different pixel formats and resolution/framerates, but these has to be entered manually. Essentially, as long as it is a file that FFmpeg can decode, it should work as an input, but you might have to dig a bit in your files to get the input parameters. Look in the reference code to see how the model can be used. 

Finally, there is a ITU-T technical report describing the model where you can get more information about 
https://www.itu.int/pub/T-TUT-OPAVQ-2019-PSNTR

**Comment by chatdeschroedinger** [comment]
For anybody trying to set this up in a conda environment.
What has worked for me on an Apple Silicon M1 Macbook Pro 16GB RAM 2021

- install anaconda
- run the following commands:
`conda update anaconda`
`conda --version` —> should return conda 4.11.0
`conda create -n myenv python=3.6`
`conda activate myenv`
`conda install tensorflow`
`conda install h5py`
`conda install numpy`
`conda install scikit-image`
`python3 PXNR-model.py`

Running the model on the provided BigBunny clip takes about 1.5h


For using a singularity container use:

Bootstrap: docker
From: ubuntu:20.04

%post
  apt-get -y update
  apt-get install -y software-properties-common
  apt-get -y update
  apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip pulseaudio xauth
  apt-get install -y ubuntu-drivers-common
  apt-get install -y libssl-dev
  apt-get install -y bc
  apt-get install -y python3-pip
  pip3 --version
  yes | pip3 install scikit-image
  yes | pip3 install tensorflow
  yes | pip3 install numpy
  yes | pip3 install h5py
  apt-get install -y ffmpeg

Running this on a 500GB RAM server with 128 cores requires ca 15min with the provided Big Bunny
